In [176]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

from IPython.core.display import display

import os, sys
SRC_PATH = os.path.abspath("../src")
if SRC_PATH not in sys.path:
    sys.path.append(SRC_PATH)

import numpy as np


In [24]:
a = np.zeros([2,8,8], dtype=np.float)

In [25]:
a.reshape((1,2,8,8))[0].shape

(2, 8, 8)

In [28]:
from reversi_zero.env.reversi_env import ReversiEnv, Player

In [29]:
env = ReversiEnv().reset()


In [31]:
env.next_player == Player.white

False

In [32]:
np.zeros((8,))

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [68]:
mask = 0xfedcba9876543210
z = np.array(range(64))

In [89]:
from timeit import timeit

#mask_array = np.array([(mask >> (i*4)) & 0xFF for i in range(16)], dtype=np.uint8)
#np.unpackbits(mask_array).reshape((-1, 8))

def impl1():
    return np.array(list(reversed(bin(mask)[2:])), dtype=int) * z

impl1

In [93]:
timeit("impl1()", number=10000, globals=locals())

0.1212078370153904

In [112]:
def bit_to_array(x, size):
    """bit_to_array(0b0010, 4) -> array([0, 1, 0, 0])"""
    return np.array(list(reversed( (("0" * size) + bin(x)[2:])[-size:])), dtype=np.uint8)

timeit("bit_to_array(0b10010, 8)", number=10000, globals=locals())

0.03786197898443788

In [111]:
bit_to_array(0b10010, 8)

array([0, 1, 0, 0, 1, 0, 0, 0], dtype=uint8)

In [113]:
np.sqrt(2)

1.4142135623730951

In [116]:
x1 = np.arange(64).reshape((8,8))
np.array([x1, x1]).shape

(2, 8, 8)

In [118]:
from collections import namedtuple
CounterKey = namedtuple("CounterKey", "black white next_player")


In [120]:
ck = CounterKey(1, 2, 3)

In [182]:
np.round(np.random.dirichlet([0.03] * 8) * 1000)

array([   0.,  749.,  251.,    0.,    0.,    0.,    0.,    0.])

In [145]:
a = np.arange(4)
np.power(a, 1/0.01)

array([  0.00000000e+00,   1.00000000e+00,   1.26765060e+30,
         5.15377521e+47])

In [156]:
from collections import Counter

v = [0,1,0,0,0]
nb_actions = len(v)
probs = np.array(v) / np.sum(v)
s = np.random.choice(range(nb_actions), 150, p=probs)
Counter(s)

Counter({1: 150})

In [162]:
from datetime import datetime 
datetime.now().strftime("%Y%m%d-%H%M%S.%f")

'20171021-232254.180040'

In [198]:
from reversi_zero.lib.bitboard import *

ob = b = 0x000000000000000F
b = flip_vertical(b)
bit_to_array(b, 64).reshape((8,8))

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0]], dtype=uint8)

In [199]:
z = bit_to_array(ob, 64)
z.reshape((8,8))

array([[1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [211]:
np.rot90(z.reshape((8,8)), k=3)

array([[0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [208]:
np.flipud(z.reshape((8,8)))

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0]], dtype=uint8)