In [2]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

from IPython.core.display import display

import os, sys
SRC_PATH = os.path.abspath("../src")
if SRC_PATH not in sys.path:
    sys.path.append(SRC_PATH)

import numpy as np


In [2]:
a = np.zeros([2,8,8], dtype=np.float)

In [6]:
from timeit import timeit

def dirichlet_impl1():
    return np.random.dirichlet([0.5] * 64)

timeit("dirichlet_impl1()", number=10000, globals=locals())

0.16099384799963445

In [50]:
from reversi_zero.lib.bitboard import bit_count, bit_to_array

legal_moves = 742389


def dirichlet_impl2(lm):
    num_1 = bit_count(lm)
    noise = list(np.random.dirichlet([0.5] * num_1))
    ret_list = []
    for i in range(64):
        if (1 << i) & lm:
            ret_list.append(noise.pop(0))
        else:
            ret_list.append(0)
    return np.array(ret_list)


print(bit_count(legal_moves))
print(bit_to_array(legal_moves, 64).reshape((8, 8)))
d2 = dirichlet_impl2(legal_moves).reshape((8, 8))
print(d2)
timeit("dirichlet_impl2(legal_moves)", number=10000, globals=locals())

13
[[1 0 1 0 1 1 1 1]
 [1 1 0 0 1 0 1 0]
 [1 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[ 0.28476908  0.          0.18926064  0.          0.03669978  0.08093667
   0.04656825  0.08019153]
 [ 0.03939774  0.02279583  0.          0.          0.04095987  0.
   0.04179759  0.        ]
 [ 0.11997698  0.00075085  0.          0.01589518  0.          0.          0.
   0.        ]
 [ 0.          0.          0.          0.          0.          0.          0.
   0.        ]
 [ 0.          0.          0.          0.          0.          0.          0.
   0.        ]
 [ 0.          0.          0.          0.          0.          0.          0.
   0.        ]
 [ 0.          0.          0.          0.          0.          0.          0.
   0.        ]
 [ 0.          0.          0.          0.          0.          0.          0.
   0.        ]]


0.34761858899946674

2

In [112]:
def bit_to_array(x, size):
    """bit_to_array(0b0010, 4) -> array([0, 1, 0, 0])"""
    return np.array(list(reversed( (("0" * size) + bin(x)[2:])[-size:])), dtype=np.uint8)

timeit("bit_to_array(0b10010, 8)", number=10000, globals=locals())

0.03786197898443788

In [111]:
bit_to_array(0b10010, 8)

array([0, 1, 0, 0, 1, 0, 0, 0], dtype=uint8)

In [113]:
np.sqrt(2)

1.4142135623730951

In [116]:
x1 = np.arange(64).reshape((8,8))
np.array([x1, x1]).shape

(2, 8, 8)

In [118]:
from collections import namedtuple
CounterKey = namedtuple("CounterKey", "black white next_player")


In [120]:
ck = CounterKey(1, 2, 3)

In [182]:
np.round(np.random.dirichlet([0.03] * 8) * 1000)

array([   0.,  749.,  251.,    0.,    0.,    0.,    0.,    0.])

In [145]:
a = np.arange(4)
np.power(a, 1/0.01)

array([  0.00000000e+00,   1.00000000e+00,   1.26765060e+30,
         5.15377521e+47])

In [156]:
from collections import Counter

v = [0,1,0,0,0]
nb_actions = len(v)
probs = np.array(v) / np.sum(v)
s = np.random.choice(range(nb_actions), 150, p=probs)
Counter(s)

Counter({1: 150})

In [162]:
from datetime import datetime 
datetime.now().strftime("%Y%m%d-%H%M%S.%f")

'20171021-232254.180040'

In [198]:
from reversi_zero.lib.bitboard import *

ob = b = 0x000000000000000F
b = flip_vertical(b)
bit_to_array(b, 64).reshape((8,8))

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0]], dtype=uint8)

In [199]:
z = bit_to_array(ob, 64)
z.reshape((8,8))

array([[1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [211]:
np.rot90(z.reshape((8,8)), k=3)

array([[0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

In [208]:
np.flipud(z.reshape((8,8)))

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0]], dtype=uint8)