In [23]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

from IPython.core.display import display

import os, sys
SRC_PATH = os.path.abspath("../src")
if SRC_PATH not in sys.path:
    sys.path.append(SRC_PATH)

import numpy as np


In [24]:
a = np.zeros([2,8,8], dtype=np.float)

In [25]:
a.reshape((1,2,8,8))[0].shape

(2, 8, 8)

In [28]:
from reversi_zero.env.reversi_env import ReversiEnv, Player

In [29]:
env = ReversiEnv().reset()


In [31]:
env.next_player == Player.white

False

In [32]:
np.zeros((8,))

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [68]:
mask = 0xfedcba9876543210
z = np.array(range(64))

In [89]:
from timeit import timeit

#mask_array = np.array([(mask >> (i*4)) & 0xFF for i in range(16)], dtype=np.uint8)
#np.unpackbits(mask_array).reshape((-1, 8))

def impl1():
    return np.array(list(reversed(bin(mask)[2:])), dtype=int) * z

impl1

In [93]:
timeit("impl1()", number=10000, globals=locals())

0.1212078370153904

In [112]:
def bit_to_array(x, size):
    """bit_to_array(0b0010, 4) -> array([0, 1, 0, 0])"""
    return np.array(list(reversed( (("0" * size) + bin(x)[2:])[-size:])), dtype=np.uint8)

timeit("bit_to_array(0b10010, 8)", number=10000, globals=locals())

0.03786197898443788

In [111]:
bit_to_array(0b10010, 8)

array([0, 1, 0, 0, 1, 0, 0, 0], dtype=uint8)

In [113]:
np.sqrt(2)

1.4142135623730951

In [116]:
x1 = np.arange(64).reshape((8,8))
np.array([x1, x1]).shape

(2, 8, 8)

In [118]:
from collections import namedtuple
CounterKey = namedtuple("CounterKey", "black white next_player")


In [120]:
ck = CounterKey(1, 2, 3)

In [136]:
np.random.dirichlet([0.03] * 64)

array([  6.65384462e-12,   7.80051285e-21,   5.36088165e-31,
         7.15224127e-13,   3.17942611e-01,   3.28435705e-03,
         8.31343372e-35,   2.73462521e-05,   1.78750966e-08,
         3.04666134e-14,   1.68107575e-72,   9.56413096e-08,
         4.15880118e-30,   2.32322113e-01,   2.33826245e-39,
         1.77445799e-20,   2.40155219e-05,   5.21458945e-17,
         9.69306405e-09,   2.49421812e-37,   1.39887306e-23,
         1.16284596e-15,   4.64635248e-03,   7.65064199e-10,
         3.64225383e-21,   1.47719874e-16,   6.84168245e-15,
         1.04895753e-08,   3.62281815e-33,   1.68084464e-01,
         1.59986183e-09,   4.81750940e-19,   2.38720174e-51,
         2.58208979e-01,   4.21089414e-29,   1.65307252e-08,
         1.27312209e-05,   3.27828601e-03,   1.27366537e-09,
         4.35304251e-66,   2.35778604e-14,   2.73279918e-08,
         2.52898297e-15,   2.20102043e-12,   1.15162207e-06,
         1.21291065e-02,   3.76919764e-06,   1.99177142e-22,
         1.74757213e-06,

In [145]:
a = np.arange(4)
np.power(a, 1/0.01)

array([  0.00000000e+00,   1.00000000e+00,   1.26765060e+30,
         5.15377521e+47])

In [156]:
from collections import Counter

v = [0,1,0,0,0]
nb_actions = len(v)
probs = np.array(v) / np.sum(v)
s = np.random.choice(range(nb_actions), 150, p=probs)
Counter(s)

Counter({1: 150})

In [162]:
from datetime import datetime 
datetime.now().strftime("%Y%m%d-%H%M%S.%f")

'20171021-232254.180040'

In [163]:
import hashlib

m = hashlib.sha256()
m.update(b"jkljkljl")
m.digest()

b'\xd0\xca\x82\xea\xa1\xb17m\xb9\x8c\x07|B\x12\x96sx`+\x85x\xc2\x92o\xb3\x14g\x81Dh[v'

In [164]:
m.hexdigest()

'd0ca82eaa1b1376db98c077c4212967378602b8578c2926fb314678144685b76'

In [174]:
sh = (5,5)
ln = np.product(sh)
x1 = np.arange(ln).reshape(sh)
x2 = np.arange(ln).reshape(sh) + 4
x3 = np.arange(ln).reshape(sh) + 8
x4 = np.arange(ln).reshape(sh) + 12
x5 = np.arange(ln).reshape(sh) + 16
x6 = np.arange(ln).reshape(sh) + 20
xl = []
xl.append([x1, x2])
xl.append([x3, x4])
xl.append([x5, x6])
x = np.array(xl)


In [175]:
x.shape

(3, 2, 5, 5)

In [173]:
np.product((5,5))

25